### ISSUE TITLE
Bug report: Grayscale/color loop under certain conditions

### ISSUE THREAD

**Issue by flxapps** [flxapps/DetoxDroid#20]
Submitter: KM
When in an excluded app (color) and got to recents view on gesture navigation. Detoxdroid freaks out(app goes grayscale then color bunch of times) and freezes any interactions does not respond to touch events) until screen off then back on.

Possible solution: implement backoff when switching between color and grayscale. Wait few secs to enable or disable. Dont do anything in recents view.

Note: have animations turned off systemwide.

**Comment by flxapps** [comment]
Hello,

this issue never occured to me. Can you tell me more specifics about your Android version and device?

**Comment by anishbajpai014** [comment]
I was able to fix this by adding 
`"com.android.quickstep.RecentsActivity"`
to `ignoredEventClasses` here https://github.com/flxapps/DetoxDroid/blob/8381bcff1a5cb171565e75fb6914261d5dcf2150/app/src/main/java/com/flx_apps/digitaldetox/DetoxAccessibilityService.kt#L43

Not an ideal solution. Since the recents screen is ignored, recents screen shows the grayscale state used by the current foreground app.

**Comment by Tau5** [comment]
This has also happened to me on Android 12L, version 1.2.2 of the app

**Comment by dewittlebook** [comment]
This also seems to be affecting me
App version: fdroid 1.2.2
Device: Pixel 6a 
Android  13 TQ3A.230805.001.A2
Will attempt to learn to build and compile and try 

> I was able to fix this by adding `"com.android.quickstep.RecentsActivity"` to `ignoredEventClasses` here
