### ISSUE TITLE
Cant make last Detox droid to work

### ISSUE THREAD

**Issue by Steve4435** [flxapps/DetoxDroid#60]
Cant make Pause button and Exclude apps Sony Xoeria 5ii with latest updates
![image](https://user-images.githubusercontent.com/99252923/152967683-5163746f-ab37-4631-bd5d-a6d3321550b5.png)

**Comment by marchersimon** [comment]
Can confirm. The pause button didn't do anything and excluded apps were still in grayscale. I switched to the previous version for now. (OnePlus 7T, Android 11, downloaded from F-Droid).

**Comment by SarHawk** [comment]
![image](https://user-images.githubusercontent.com/36113207/153611727-52055f38-1ffd-4ee9-8865-0d0ac26ed138.png)

Im getting the same error with a Pixel 4 with the Latest GrapheneOS (Android 12)

I also installed it manually instead with the install script, and whenever I input the following command:

> platform-tools\adb.exe shell dpm set-device-owner com.flx_apps.digitaldetox/.DetoxDroidDeviceAdminReceiver

I get the IllegalStateException and the app can't deactivate other apps.

**Comment by schnps** [comment]
Same issue here when setting owner.

Running CalyxOS, so I assume CalyxOS is blocking this for security reasons.

**Comment by whatisthisidont** [comment]
I'm getting the same error:
`Not allowed to set the device owner because there are already several users on the device`

Huawei P10 with EMUI 9.1.0 (Android 9).

**Comment by coderamm** [comment]
I can confirm I am getting the same error. App version v1.2.2 Android 12 Build 00WW_2_2300.

[This discussion](https://stackoverflow.com/questions/44155652/not-allowed-to-set-the-device-owner-because-there-are-already-several-users-on-t) on SO suggests that this command only works when there are no accounts signed in on the device. But removing all accounts and adding them later seems like a poor solution.
